sudo: required

language: python

python:
  - "2.7"

services:
  - docker

env:
  - OMEROBUILD=OMERO-DEV-merge-build SKIP_UPGRADE_CHECK=true
  - OMEROBUILD=OMERO-DEV-latest SKIP_UPGRADE_CHECK=true
  - RELEASE=true # test default

before_install:
  - pip install docker-compose
  - docker-compose -v

script:
  - ./runtest
